@url = http://localhost:8017/v1/dashboards
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRydW5ncXVhbmRldi1zYW1wbGUtaWQtMTIzNDU2NzgiLCJlbWFpbCI6InRydW5ncXVhbmRldi5vZmZpY2lhbEBnbWFpbC5jb20iLCJyb2xlIjpbIm1vZGVyYXRvciJdLCJpYXQiOjE3NTcxMzg0MTcsImV4cCI6MTc1NzE0MjAxN30.-9afczWxcCipTZ3zKNyhATbruCpKHRAeD2anbMpM04M
### dashboard access
GET {{url}}/access
Content-Type: application/json
Authorization: Bearer {{access_token}}

### get /message
GET {{url}}/messages
Content-Type: application/json
Authorization: Bearer {{access_token}}

### get /admin-tools
GET {{url}}/admin-tools
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get /support
GET {{url}}/support
Content-Type: application/json
Authorization: Bearer {{access_token}}