version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "80:80"
    depends_on:
      - mongodb
    env_file:
      - ./env/backend.env
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    tty: true
    stdin_open: true
volumes:
  data:
  logs: