### Sign up the users
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "ngocbao123steam@gmail.com",
  "password": "123456"
}

### get user by id
GET http://localhost:3000/auth/users/4

### find user by email
GET http://localhost:3000/auth/users?email=ngocbao123steam@gmail.com

### Delete user by id
DELETE http://localhost:3000/auth/users/1

### Update user by id
PATCH http://localhost:3000/auth/users/1
Content-Type: application/json

{
  "email": "bao@gmail.com",
  "password": "123456789"
}